Desafio AP Coders/MvcWebApp/Models/DespesaDaUnidade.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace mvc_web_app.Models
{
    [Table("DespesasDasUnidades")]
    public class DespesaDaUnidade
    {
        [Key()]
        public int id { get; set; }
        [Display(Name = "Descrição"), Required()]
        public string descricao { get; set; }
        [Display(Name = "Tipo de despesa"), Required()]
        public string tipoDespesa { get; set; }
        [Display(Name = "Valor"), Required()]
        public float valor { get; set; }
        [Display(Name = "Data  de vencimento"), Required(), DataType(DataType.Date)]
        public DateTime vencimento_fatura { get; set; }
        [Display(Name = "Status do pagamento"), Required()]
        public string statusPagamento { get; set; }
        [Display(Name = "Unidade"), Required()]
        public string unidadeId { get; set; }

    }
}

Desafio AP Coders/MvcWebApp/Controllers/DespesasDasUnidadesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_web_app;
using mvc_web_app.Models;

namespace mvc_web_app.Controllers
{
    public class DespesaDaUnidadeController : Controller
    {
        private readonly MvcWebAppContext _context;

        public DespesaDaUnidadeController(MvcWebAppContext context)
        {
            _context = context;
        }

        // GET: DespesaDaUnidade

        public async Task<IActionResult> Index(string unidade, DateTime vencimento)
        {
            CarregaStatusDePagamentosDropDownList();
            CarregaTiposDeDespesas();
            IQueryable<DateTime> vencimentosdeQuery = from m in _context.DespesasDasUnidades orderby m.vencimento_fatura select m.vencimento_fatura;

            var despesaDaUnidade = from m in _context.DespesasDasUnidades select m;

            if (vencimento != default)
            {
                despesaDaUnidade = despesaDaUnidade.Where(s => s.vencimento_fatura == vencimento);
            }
            if (!string.IsNullOrEmpty(unidade))
            {
                despesaDaUnidade = despesaDaUnidade.Where(s => s.unidadeId.Contains(unidade));
            }

            var despesaDaUnidadeVM = new DespesasDasUnidadesViewModel();

            despesaDaUnidadeVM.DespesasDasUnidades = await despesaDaUnidade.ToListAsync();
            despesaDaUnidadeVM.Vencimentos = new SelectList(await vencimentosdeQuery.Distinct().ToListAsync());
            CarregaStatusDePagamentosDropDownList();
            CarregaTiposDeDespesas();

            return View(despesaDaUnidadeVM);
        }

        // GET: DespesaDaUnidade/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despesaDaUnidade = await _context.DespesasDasUnidades
                .FirstOrDefaultAsync(m => m.id == id);
            if (despesaDaUnidade == null)
            {
                return NotFound();
            }

            return View(despesaDaUnidade);
        }

        // GET: DespesaDaUnidade/Create
        public IActionResult Create()
        {
            CarregaUnidadesDropDownList();
            CarregaTiposDeDespesas();
            CarregaStatusDePagamentosDropDownList();
            return View();
        }

        // POST: DespesaDaUnidade/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,descricao,tipoDespesa,valor,vencimento_fatura,statusPagamento,unidadeId")] DespesaDaUnidade despesaDaUnidade)
        {
            if (ModelState.IsValid)
            {
                _context.Add(despesaDaUnidade);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            CarregaUnidadesDropDownList();
            CarregaStatusDePagamentosDropDownList();
            CarregaTiposDeDespesas();
            return View(despesaDaUnidade);
        }

        // GET: DespesaDaUnidade/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despesaDaUnidade = await _context.DespesasDasUnidades.FindAsync(id);
            if (despesaDaUnidade == null)
            {
                return NotFound();
            }
            CarregaUnidadesDropDownList();
            CarregaStatusDePagamentosDropDownList();
            CarregaTiposDeDespesas();
            return View(despesaDaUnidade);
        }

        // POST: DespesaDaUnidade/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,descricao,tipoDespesa,valor,vencimento_fatura,statusPagamento,unidadeId")] DespesaDaUnidade despesaDaUnidade)
        {
            if (id != despesaDaUnidade.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(despesaDaUnidade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DespesaDaUnidadeExists(despesaDaUnidade.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            CarregaUnidadesDropDownList();
            CarregaStatusDePagamentosDropDownList();
            CarregaTiposDeDespesas();
            return View(despesaDaUnidade);
        }

        // GET: DespesaDaUnidade/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var despesaDaUnidade = await _context.DespesasDasUnidades
                .FirstOrDefaultAsync(m => m.id == id);
            if (despesaDaUnidade == null)
            {
                return NotFound();
            }

            return View(despesaDaUnidade);
        }

        // POST: DespesaDaUnidade/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var despesaDaUnidade = await _context.DespesasDasUnidades.FindAsync(id);
            _context.DespesasDasUnidades.Remove(despesaDaUnidade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DespesaDaUnidadeExists(int id)
        {
            return _context.DespesasDasUnidades.Any(e => e.id == id);
        }
        public void CarregaStatusDePagamentosDropDownList()
        {
            ViewData["statusPagamento"] = new SelectList(Enum.GetValues(typeof(StatusDosPagamentos)));
        }
        public void CarregaTiposDeDespesas()
        {
            ViewData["tipoDespesa"] = new SelectList(Enum.GetValues(typeof(TiposDeDespesas)));
        }

        public void CarregaUnidadesDropDownList()
        {
            ViewData["unidades"] = new SelectList(_context.Unidades, "indentificacao", "indentificacao");   
        }
    }
}

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/Create.cshtml
@model mvc_web_app.Models.DespesaDaUnidade

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Despesas Das Unidades</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label"></label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipoDespesa" class="control-label"></label>
                <select asp-for="tipoDespesa" class="form-control" asp-items=ViewBag.tipoDespesa></select>
                <span asp-validation-for="tipoDespesa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valor" class="control-label"></label>
                <input asp-for="valor" class="form-control" />
                <span asp-validation-for="valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vencimento_fatura" class="control-label"></label>
                <input asp-for="vencimento_fatura" class="form-control"/>
                <span asp-validation-for="vencimento_fatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="statusPagamento" class="control-label"></label>
                <select asp-for="statusPagamento" class="form-control" asp-items=ViewBag.statusPagamento></select>
                <span asp-validation-for="statusPagamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="unidadeId" class="control-label"></label>
                <select asp-for="unidadeId" class="form-control"  asp-items=ViewBag.unidades></select>
                <span asp-validation-for="unidadeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/Delete.cshtml
@model mvc_web_app.Models.DespesaDaUnidade

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DespesaDaUnidade</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipoDespesa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipoDespesa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vencimento_fatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vencimento_fatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.statusPagamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.statusPagamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.unidadeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.unidadeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/Details.cshtml
@model mvc_web_app.Models.DespesaDaUnidade

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DespesaDaUnidade</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tipoDespesa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tipoDespesa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vencimento_fatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vencimento_fatura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.statusPagamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.statusPagamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.unidadeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.unidadeId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/Edit.cshtml
@model mvc_web_app.Models.DespesaDaUnidade

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DespesaDaUnidade</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="descricao" class="control-label"></label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipoDespesa" class="control-label"></label>
                <select asp-for="tipoDespesa" class="form-control" asp-items="ViewBag.tipoDespesa"></select>
                <span asp-validation-for="tipoDespesa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="valor" class="control-label"></label>
                <input asp-for="valor" class="form-control" />
                <span asp-validation-for="valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vencimento_fatura" class="control-label"></label>
                <input asp-for="vencimento_fatura" class="form-control" />
                <span asp-validation-for="vencimento_fatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="statusPagamento" class="control-label"></label>
                <select asp-for="statusPagamento" class="form-control" asp-items="ViewBag.statusPagamento"></select>
                <span asp-validation-for="statusPagamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="unidadeId" class="control-label"></label>
                <select asp-for="unidadeId" class="form-control" asp-items="ViewBag.unidades"></select>
                <span asp-validation-for="unidadeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/Index.cshtml
@model mvc_web_app.Models.DespesasDasUnidadesViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="DespesaDaUnidade" asp-action="Index" method="get">
    <p>

        Vencimento: <input type="date" asp-for="vencimento"/>

        Unidade: <input type="text" asp-for="unidade" />
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].tipoDespesa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].vencimento_fatura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].statusPagamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DespesasDasUnidades[0].unidadeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.DespesasDasUnidades)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipoDespesa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vencimento_fatura)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.statusPagamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.unidadeId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Desafio AP Coders/MvcWebApp/Views/DespesaDaUnidade/IndexX.cshtml
@model IEnumerable<mvc_web_app.Models.DespesaDaUnidade>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="DespesaDaUnidade" asp-action="Index">
    <p>
        Unidade: <input type="text" name="searchString" />
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tipoDespesa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.vencimento_fatura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.statusPagamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.unidadeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoDespesa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vencimento_fatura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.statusPagamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.unidadeId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>